name: Windows Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Deploy to Windows Server
        run: |
          echo "Deploy"
          # Ejemplo:
          Copy-Item -Path ".\Preproduccion\*" -Destination "C:\Users\pmimarc\Desktop\Projects\Pruebas-CI" -Force -Recurse
        
